### ISSUE TITLE
Node 生成缩略图

### ISSUE THREAD

**Issue by LH0702** [LH0702/Single-learn#1]
node-webshot
地址 :https://github.com/brenden/node-webshot

Example
```xml
var webshot = require('webshot');

webshot('google.com', 'google.png', function(err) {
  // screenshot now saved to google.png
});
```

**Comment by suiqingxian** [comment]
html2canvas生成缩略图
```xml
The script doesn't render plugin content such as Flash or Java applets. It doesn't render iframe content either.
```

**Comment by suiqingxian** [comment]
### 读书日记
 流程控制库： async, step, eventProxy,wind

**Comment by suiqingxian** [comment]
### let var的区别
```
for(var i = 0;i<3;i++){
 setTimeout(function(){
   console.log(i)
 },1000)
}

for(let i = 0;i<3;i++){
 setTimeout(function(){
   console.log(i)
 },1000)
}
```
第二种用法可以避免bug，var变量作用域和let不同。第一种方式控制台打印 2 2 2，原因是多次循环共享一个变量。循环结束后延时函数执行，这时i 的值已经变成2。  采用第二种方法，循环保持一个闭包，每一个闭包都是捕获循环变量的不通知做副本，而不是所有的闭包都捕获循环变量的同一值。
类似第一种方式，

**Comment by suiqingxian** [comment]
欢迎留言

**Comment by mangojunian** [comment]
hello,my sweetier XiaoChunHuo ! I find you eventually，if this isn‘t yours,it will be embarrassing.

**Comment by mangojunian** [comment]
啊，看到上面才意识到，这个能发中文啊！！！！  I Love Chinese ，，，and You，especially You,,(*^__^*) ……

**Comment by suiqingxian** [comment]
:cupid:  :stuck_out_tongue_closed_eyes:
hello  shagou

**Comment by mangojunian** [comment]
hhhhhhhhhhhh,

**Comment by mangojunian** [comment]
- 

你的小可爱要下线了，请**小蠢货**继续工作吧，不要想我哟`

>

**Comment by suiqingxian** [comment]
:couple_with_heart_woman_man:

**Comment by mangojunian** [comment]
我刚打电话问了，要是有暂住证也能在南京异地办理，说外省拿身份证暂住证去大概办理需要一个月能下来

**Comment by mangojunian** [comment]
现在叫居住证不叫暂住证了，你回去关注南京本地宝，有指南我推荐给你了 你到时候看看。就是拿 房屋租赁登记备案证明和劳动合同（这些应该找房东要）加身份证去附近的派出所办。。微信也能办理但也许比较慢可以看看 这个是关注南京公安的公众号有微服务-户政  申请办理，也推荐给你了。总之你先要去房东那拿到那些材料吧

**Comment by suiqingxian** [comment]
好的

**Comment by suiqingxian** [comment]
zai?

**Comment by mangojunian** [comment]
哎呦，把我的留言删了

**Comment by suiqingxian** [comment]
都能看见

**Comment by mangojunian** [comment]
啊

**Comment by mangojunian** [comment]
371083198007278534   刘
ljb99999

370630196511234514    尹
rsk123123

370630196306110053   丁
ding123456

37063019600319451X   于
rsk123123


林夕峰
371021197304126074。lxf412816


张红军
37063019710404251X。zhang123456

宋健
371021196301280055。song123456

**Comment by mangojunian** [comment]
XIAOGEGE

**Comment by mangojunian** [comment]
小哥哥不上线了
