### ISSUE TITLE
java 学习概要

### ISSUE THREAD

**Issue by LH0702** [LH0702/Single-learn#5]
参考书目《java 编程思想》
ide 使用  intellij IDEA
JDK 使用 JDK 1.8
建议使用maven 工程，便于下载开源软件

**Comment by suiqingxian** [comment]
- 概论 面向对象的编程
  - 类的概念，一切皆是对象
  - 继承 多态
  - 容器 list hash set
  - 对象创建和生命周期
  - 异常处理

**Comment by suiqingxian** [comment]
### 进阶

**Comment by mangojunian** [comment]
Thanks my teacher~~
